matrix:
  include:
    - os: linux
      services:
      - docker
      env: TARGET=debian-jessie
      env: TARGET=debian-testing
      env: TARGET=debian-unstable
      env: TARGET=ubuntu-trusty
      env: TARGET=ubuntu-xenial
      env: TARGET=ubuntu-yakkety
      env: TARGET=debian-pip
    - os: osx

sudo: required
script:
- ./build-and-run.sh $TARGET $TRAVIS_OS_NAME
