matrix:
    include:
        - env: TARGET=debian-jessie
        - env: TARGET=debian-testing
        - env: TARGET=debian-unstable
        - env: TARGET=ubuntu-trusty
        - env: TARGET=ubuntu-xenial
        - env: TARGET=ubuntu-yakkety
        - env: TARGET=debian-pip
        - os: osx
          osx_image: xcode6.4
        - os: osx
          osx_image: xcode7.3
        - os: osx
          osx_image: xcode8
        - os: osx
          osx_image: xcode8.1
        - os: osx
          osx_image: xcode8.2

sudo: required
services:
- docker
script:
- ./build-and-run.sh $TARGET $TRAVIS_OS_NAME
