env:
  matrix:
  - TARGET=debian-jessie
  - TARGET=debian-testing
  - TARGET=debian-unstable
  - TARGET=ubuntu-trusty
  - TARGET=ubuntu-xenial
  - TARGET=ubuntu-yakkety
  - TARGET=debian-pip

- os: linux
  services:
  - docker
- os: osx

- matrix:
    exclude:
    - os: osx

sudo: required
script:
- ./build-and-run.sh $TARGET $TRAVIS_OS_NAME
