matrix:
    include:
        - os: linux
          dist: trusty
          env: TARGET=debian-jessie
        - os: linux
          dist: trusty
          env: TARGET=debian-testing
        - os: linux
          dist: trusty
          env: TARGET=debian-unstable
        - os: linux
          dist: trusty
          env: TARGET=ubuntu-trusty
        - os: linux
          dist: trusty
          env: TARGET=ubuntu-xenial
        - os: linux
          dist: trusty
          env: TARGET=ubuntu-yakkety
        - os: linux
          dist: trusty
          env: TARGET=debian-pip
        - os: osx

sudo: required
services:
- docker
script:
- ./build-and-run.sh ${TRAVIS_OS_NAME} ${TARGET}
