matrix:
    include:
        - os: linux
          services:
          - docker
          env:
          - TARGET=debian-jessie
          - TARGET=debian-testing
          - TARGET=debian-unstable
          - TARGET=ubuntu-trusty
          - TARGET=ubuntu-xenial
          - TARGET=ubuntu-yakkety
          - TARGET=debian-pip
        - os: osx
          osx_image:
          - xcode6.4
          - xcode7.3
          - xcode8
          - xcode8.1
          - xcode8.2

sudo: required
script:
- ./build-and-run.sh $TARGET $TRAVIS_OS_NAME
